import streamlit as st
import time

st.set_page_config(
    page_title="BeyondForge | DevPersona Simulator",
    page_icon="🚀",
    layout="wide"
)

st.title("🚀 BeyondForge: DevPersona Simulator")
st.caption("Autonomous Multi-Agent Developer Simulation & Code Review Engine powered by IBM Bob 2.0")

st.markdown("---")

col_code, col_review = st.columns([1, 1])

with col_code:
    st.subheader("💻 Code Submission")
    default_code = '''def get_user_records(user_id):
    # Fetch user records from database
    query = "SELECT * FROM users WHERE id = " + str(user_id)
    results = db.execute(query)
    
    for r in results:
        process_transaction(r)
        
    return results'''
    
    code_input = st.text_area("Paste code snippet / Pull Request diff here:", value=default_code, height=320)
    simulate_btn = st.button("⚡ Run Multi-Agent Persona Simulation", type="primary")

with col_review:
    st.subheader("👥 Simulated Engineering Round-Table")
    
    if simulate_btn:
        with st.spinner("Orchestrating IBM Bob 2.0 subagent debate..."):
            time.sleep(1.2)
            
        st.success("✅ Multi-Agent Simulation Complete!")
        
        # Checking if the code has best-practice indicators
        is_clean_code = ("try:" in code_input or "os.getenv" in code_input or "logger" in code_input) and ("SELECT *" not in code_input and "API_KEY" not in code_input)
        
        if is_clean_code:
            # High Score State (Clean Code)
            st.metric(label="Merge Confidence Score", value="96%", delta="+58% (Approved for Merge)")
            st.balloons()
            st.markdown("---")
            
            with st.expander("🛡️ Alex Vance (Security Lead) - [CLEAN / APPROVED]", expanded=True):
                st.success("Verdict: No hardcoded secrets or raw query concatenations found. Secure authorization handled.")
                
            with st.expander("👶 Leo Miller (Junior Developer) - [EXCELLENT]", expanded=True):
                st.success("Verdict: Clear type hints and docstrings present. Readability cognitive load is optimal.")

            with st.expander("⚡ Marcus Kane (Principal SRE) - [RESILIENT]", expanded=True):
                st.success("Verdict: Managed session pooling and strict timeouts detected. Safe for high-concurrency production.")

            with st.expander("💥 Raven Quinn (QA Chaos Monkey) - [BULLETPROOF]", expanded=True):
                st.success("Verdict: Explicit parameter validation and defensive exception handling prevent runtime crashes.")
                
            st.markdown("---")
            st.info("🎉 Code passes all 4 persona gates. Ready for immediate production merge!")

        else:
            # Low Score State (Vulnerable/Flawed Code)
            st.metric(label="Merge Confidence Score", value="38%", delta="-62% (Blocked)")
            st.markdown("---")
            
            with st.expander("🛡️ Alex Vance (Security Lead) - [CRITICAL VULNERABILITY]", expanded=True):
                st.error("Flag: Critical Security Risk Detected!")
                st.write("Identified unescaped dynamic payload or hardcoded sensitive token. Risk of injection/credential breach.")
                
            with st.expander("👶 Leo Miller (Junior Developer) - [CONFUSED / HIGH FRICTION]", expanded=True):
                st.warning("Flag: Readability & Documentation Deficit")
                st.write("Missing parameter type hints, ambiguous variable structures, and absent docstrings.")

            with st.expander("⚡ Marcus Kane (Principal SRE) - [RUNTIME LATENCY WARNING]", expanded=True):
                st.warning("Flag: Resource Leak / Thread Blocking Danger")
                st.write("Unbounded I/O operations without timeouts will cause thread exhaustion under production traffic.")

            with st.expander("💥 Raven Quinn (QA Chaos Monkey) - [EXCEPTION BREACH]", expanded=True):
                st.error("Flag: Unhandled Edge Case Trap")
                st.write("Null pointers, missing payload keys, or network failures will bubble up as unhandled runtime errors.")
                
            st.markdown("---")
            st.subheader("🤖 IBM Bob 2.0 Automated Remediation Patch")
            st.code('''# Refactored with parameterized queries, env tokens & error handling
import os, requests

def safe_handler(payload_data: dict) -> dict:
    """Production-grade hardened handler generated by IBM Bob 2.0."""
    token = os.getenv("API_TOKEN")
    if not token or not payload_data:
        raise ValueError("Invalid parameters or missing credentials")
        
    with requests.Session() as session:
        res = session.post("https://api.service.internal/v1", json=payload_data, timeout=5)
        res.raise_for_status()
        return res.json()''', language="python")

    else:
        st.info("Click 'Run Multi-Agent Persona Simulation' to initiate review.")
